"""News -- daily MLB/MiLB feed: external headlines + TDD-generated stories.

Private-trial page: unlisted (not in the nav) and key-gated. When a
``news_access_key`` is configured (Streamlit secrets or ``NEWS_ACCESS_KEY``
env var), the page requires ``?page=news&key=<value>`` once per session.
With no key configured (local dev), the page is open.
"""

from __future__ import annotations

import os

import pandas as pd
import streamlit as st
from services.data_loader import load_news_feed
from utils.alerts import tdd_info
from utils.html import esc, esc_attr

# Category -> (display label, badge color)
_CATEGORY_META: dict[str, tuple[str, str]] = {
    "headline": ("Headline", "#C8A96E"),
    "prospect": ("Prospects", "#4FC3C8"),
    "injury": ("Injury", "#D9705B"),
    "transaction": ("Transaction", "#7B8FA6"),
    "hot_streak": ("Hot Streak", "#D9A05B"),
    "cold_streak": ("Cold Streak", "#6FA8DC"),
    "standout_hitter": ("Standout Bat", "#C8A96E"),
    "standout_pitcher": ("Standout Arm", "#C8A96E"),
    "promotion": ("Promotion", "#4FC3C8"),
    "demotion": ("Demotion", "#7B8FA6"),
    "debut": ("MLB Debut", "#4FC3C8"),
    "milestone": ("Milestone", "#C8A96E"),
}

_MAIN_CATEGORIES = [
    "hot_streak",
    "cold_streak",
    "standout_hitter",
    "standout_pitcher",
    "milestone",
]
_RAIL_INJURY_CATEGORIES = ["injury", "transaction"]
_RAIL_PROSPECT_CATEGORIES = ["debut", "promotion", "demotion", "prospect"]


def _badge(category: str) -> str:
    label, color = _CATEGORY_META.get(category, (category, "#7B8FA6"))
    return (
        f'<span style="background:{color}22;color:{color};border:1px solid {color};'
        f"border-radius:4px;padding:1px 7px;font-size:11px;font-weight:600;"
        f'white-space:nowrap;">{esc(label)}</span>'
    )


def _story_html(row: pd.Series, show_badge: bool = True) -> str:
    headline = esc(row["headline"])
    link = row.get("link")
    if pd.notna(link) and link:
        head = (
            f'<a href="{esc_attr(link)}" target="_blank" '
            f'style="color:var(--tdd-cream);font-weight:600;text-decoration:none;">'
            f"{headline}</a>"
        )
    elif pd.notna(row.get("player_id")):
        pid = int(row["player_id"])
        head = (
            f'<a href="?page=player_profile&player_id={pid}" target="_self" '
            f'style="color:var(--tdd-cream);font-weight:600;text-decoration:none;">'
            f"{headline}</a>"
        )
    else:
        head = f'<span style="color:var(--tdd-cream);font-weight:600;">{headline}</span>'

    badge = f"{_badge(row['category'])} " if show_badge else ""
    blurb = str(row["blurb"]) if pd.notna(row.get("blurb")) else ""
    blurb_html = (
        f'<div style="color:var(--tdd-slate);font-size:13px;margin-top:2px;">{esc(blurb)}</div>' if blurb else ""
    )
    return f'<div style="margin:0 0 12px 0;line-height:1.45;">{badge}{head}{blurb_html}</div>'


def _render_group(df: pd.DataFrame, title: str) -> None:
    if df.empty:
        return
    st.markdown(f"#### {title}")
    html = "".join(_story_html(row) for _, row in df.iterrows())
    st.markdown(html, unsafe_allow_html=True)


def _configured_access_key() -> str:
    """Return the access key from Streamlit secrets or env ('' if unset)."""
    try:
        key = st.secrets.get("news_access_key", "")
    except Exception:  # no secrets.toml in local dev
        key = ""
    return str(key or os.environ.get("NEWS_ACCESS_KEY", "")).strip()


def _has_access() -> bool:
    """Gate the page behind ?key=<news_access_key> when a key is configured.

    Access sticks for the session so navigating within the app does not
    require re-supplying the key.
    """
    expected = _configured_access_key()
    if not expected:
        return True
    if st.session_state.get("news_access_ok", False):
        return True
    if st.query_params.get("key", "") == expected:
        st.session_state["news_access_ok"] = True
        return True
    return False


def page_news() -> None:
    if not _has_access():
        # Indistinguishable from a nonexistent page -- no hint that a key
        # would unlock it.
        tdd_info("Page not found.")
        return

    st.markdown(
        '<div style="display:inline-block;background:#D9705B22;color:#D9705B;'
        "border:1px solid #D9705B;border-radius:4px;padding:2px 10px;"
        'font-size:12px;font-weight:700;letter-spacing:2px;margin-bottom:4px;">'
        "EXPERIMENTAL</div>",
        unsafe_allow_html=True,
    )
    st.title("News")

    feed = load_news_feed()
    if feed.empty:
        tdd_info("No news yet — the feed is generated by the morning pipeline.")
        return

    feed = feed.copy()
    feed["feed_date"] = pd.to_datetime(feed["feed_date"])

    # --- Filter row -------------------------------------------------------
    dates = sorted(feed["feed_date"].dt.date.unique(), reverse=True)
    col_date, col_source, col_cat = st.columns([1, 1, 2])
    with col_date:
        sel_date = st.selectbox("Date", dates, index=0, format_func=lambda d: d.strftime("%a, %b %d %Y"))
    with col_source:
        sel_source = st.radio("Source", ["All", "External", "TDD Generated"], horizontal=True)
    day = feed[feed["feed_date"].dt.date == sel_date]
    with col_cat:
        present = [c for c in _CATEGORY_META if c in set(day["category"])]
        sel_cats = st.multiselect(
            "Categories",
            present,
            default=present,
            format_func=lambda c: _CATEGORY_META.get(c, (c, ""))[0],
        )

    if sel_source == "External":
        day = day[day["story_type"] == "external"]
    elif sel_source == "TDD Generated":
        day = day[day["story_type"] == "generated"]
    day = day[day["category"].isin(sel_cats)]
    day = day.sort_values(["category", "rank"])

    if day.empty:
        tdd_info("No stories match the selected filters.")
        return

    # --- Layout: main column + right rail ---------------------------------
    col_main, col_rail = st.columns([2.2, 1])

    with col_main:
        headlines = day[day["category"] == "headline"]
        if not headlines.empty:
            st.markdown("### Top Headlines")
            html = "".join(_story_html(row, show_badge=False) for _, row in headlines.sort_values("rank").iterrows())
            st.markdown(html, unsafe_allow_html=True)

        generated = day[day["category"].isin(_MAIN_CATEGORIES)]
        if not generated.empty:
            st.markdown("### Around the Diamond")
            _render_group(
                generated[generated["category"].isin(["hot_streak", "cold_streak"])],
                "Hot / Cold",
            )
            _render_group(
                generated[generated["category"].isin(["standout_hitter", "standout_pitcher"])],
                "Yesterday's Standouts",
            )
            _render_group(generated[generated["category"] == "milestone"], "Milestones")

    with col_rail:
        moves = day[day["category"].isin(_RAIL_INJURY_CATEGORIES)]
        if not moves.empty:
            st.markdown("### Injuries & Moves")
            html = "".join(_story_html(row) for _, row in moves.iterrows())
            st.markdown(html, unsafe_allow_html=True)

        prospects = day[day["category"].isin(_RAIL_PROSPECT_CATEGORIES)]
        if not prospects.empty:
            st.markdown("### Prospect Watch")
            html = "".join(_story_html(row) for _, row in prospects.iterrows())
            st.markdown(html, unsafe_allow_html=True)
